# Generated by Django 5.2.1 on 2025-05-17 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_rename_unit_measurement_ingredient_measurement_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата и время публикации",
            ),
            preserve_default=False,
        ),
    ]
