# Generated by Django 5.2.1 on 2025-05-20 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "recipes",
            "0008_alter_recipe_options_alter_recipeingredient_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.IntegerField(
                help_text="Время приготовления (в минутах), не менее 1",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Время приготовления (в минутах)",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(
                help_text="Название, не более 256 символов",
                max_length=256,
                verbose_name="Название",
            ),
        ),
    ]
