# Generated by Django 5.2.1 on 2025-05-20 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodgramuser',
            options={'ordering': ['id']},
        ),
    ]
